# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wakey' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wakey

pod 'Firebase/Analytics'
pod 'Firebase/Database'

  target 'WakeyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WakeyUITests' do
    # Pods for testing
  end

end
